### ISSUE TITLE
Gradle URL 'com.github.eltohamy:material-hijri-calendarview:1.1.0'  doesn't work on Android studio 

### ISSUE THREAD

**Issue by ymabrouk** [eltohamy/material-hijri-calendarview#1]
Gradle URL 'com.github.eltohamy:material-hijri-calendarview:1.1.0'  doesn't work on Android studio

**Comment by eltohamy** [comment]
Download the hole library now and use it while I am uploading a new version.

**Comment by ymabrouk** [comment]
Thank you for response. When will you upload the new version ?

**Comment by eltohamy** [comment]
New version added. 
Add `compile 'com.github.eltohamy:material-hijri-calendarview:1.1.0@aar'` to your dependencies.
2. Add `compile group: 'com.github.msarhan', name: 'ummalqura-calendar', version:'1.1.7'` to your dependencies.
3. Add `MaterialHijriCalendarView` into your layouts or view hierarchy.
4. Set a `OnDateSelectedListener` or call `MaterialHijriCalendarView.getSelectedDates()` when you need it.

**Comment by leducaminou** [comment]
Hello i have downloaded the new version of your library, 
for mine, only Custumise xml is working.

**Comment by eltohamy** [comment]
What is the issue you have?
