### ISSUE TITLE
Error inflating class com.github.eltohamy.materialhijricalendarview.MaterialHijriCalendarView

### ISSUE THREAD

**Issue by Darasaini** [eltohamy/material-hijri-calendarview#10]
Error inflating class com.github.eltohamy.materialhijricalendarview.MaterialHijriCalendarView
android.view.LayoutInflater.createView (LayoutInflater.java:640)
android.view.LayoutInflater.createViewFromTag (LayoutInflater.java:750)
android.view.LayoutInflater.rInflate (LayoutInflater.java:813)
android.view.LayoutInflater.rInflate (LayoutInflater.java:821)
android.view.LayoutInflater.rInflate (LayoutInflater.java:821)
android.view.LayoutInflater.rInflate (LayoutInflater.java:821)
android.view.LayoutInflater.inflate (LayoutInflater.java:511)
android.view.LayoutInflater.inflate (LayoutInflater.java:415)

**Comment by eltohamy** [comment]
check you gradle file
