### ISSUE TITLE
Get Specific Day's TextView

### ISSUE THREAD

**Issue by tarlanahad** [eltohamy/material-hijri-calendarview#11]
There is no any method to get specific day's textview in order to use and setting textColor

**Comment by eltohamy** [comment]
see this sample 
https://github.com/eltohamy/material-hijri-calendarview/blob/master/sample/src/main/java/com/github/eltohamy/materialhijricalendarview/sample/BasicActivityDecorated.java

see this code BasicActivityDecorated you have to add your custom decorator
