### ISSUE TITLE
Displaying Gregorian calendar date along with Hijri Date

### ISSUE THREAD

**Issue by msadrud** [eltohamy/material-hijri-calendarview#16]
Hi,
Is the any way we can display Gregorian Calendar date along with the Hijri date?

regards,
Mohammed

**Comment by ahmadmust8** [comment]
i think you can modify [DayView.java](https://github.com/eltohamy/material-hijri-calendarview/blob/master/library/src/main/java/com/github/eltohamy/materialhijricalendarview/DayView.java) to take two calendars Gregorian calendar and Hijri calendar.
 but, it's need to change a lot of things also like [MonthView.java](https://github.com/eltohamy/material-hijri-calendarview/blob/master/library/src/main/java/com/github/eltohamy/materialhijricalendarview/MonthView.java) and of course it's Adapter and  [MaterialHijriCalendarView.java](https://github.com/eltohamy/material-hijri-calendarview/blob/master/library/src/main/java/com/github/eltohamy/materialhijricalendarview/MaterialHijriCalendarView.java)
i wish you Happy coding (:

**Comment by msadrud** [comment]
Hi Ahmad, Thanks for your reply. 
Yes, I have made some changes to reflect the Gregorian calendar. It's working but the performance is hit very badly. I will post the modifications anyway.

**Comment by ahmadmust8** [comment]
please share with me your modifications we can work on it together (:

**Comment by msadrud** [comment]
Hi Ahmad, I am extremely sorry to have missed your comments and didn't reply to you as well. Please let me know if you still need it. I will share the zip file.
