### ISSUE TITLE
Show Month names in Arabic 

### ISSUE THREAD

**Issue by SardarKhan299** [eltohamy/material-hijri-calendarview#2]
Can we show months name in Arabic or Urdu language in your library

**Comment by eltohamy** [comment]
Yes You can change them using custom_weekdays and custom_months string arrays.

**Comment by SardarKhan299** [comment]
i want to show date with respect to time zone.can i do it.? change whole calendar date with respect to time zone means in Pakistan date is changed as compared to Saudi Arab

**Comment by SardarKhan299** [comment]
can you show me the example of how to pass custom_weekdays and custom_months string arrays.

**Comment by eltohamy** [comment]
See this sample code materialhijricalendarview/sample/CustomizeCodeActivity.java

**Comment by SardarKhan299** [comment]
Thanks .also solve my another issue about date showing with respect to time zone..

**Comment by SardarKhan299** [comment]
kindly help me to solve the issue about passing date to this library.
