### ISSUE TITLE
Size of selected date circle issue

### ISSUE THREAD

**Issue by Hafijur-rahman** [eltohamy/material-hijri-calendarview#22]
Can you please explain how to change the size of selected date circle and 
how to decrease the spaces between days rows and column.

**Comment by eltohamy** [comment]
check the below and try to use the icon ic_my_default with the right width and height you need.

MaterialCalendarView widget;

widget.setTileSize(-1);
widget.setTileWidthDp(LinearLayout.LayoutParams.MATCH_PARENT);
widget.setTileHeightDp(38);
widget.addDecorator(new MySelectorDecorator(getActivity()));

public class MySelectorDecorator implements DayViewDecorator {
private final Drawable drawable;
public MySelectorDecorator(Activity context) {
drawable = context.getResources().getDrawable(R.drawable.my_selector_default);
}
@override
public boolean shouldDecorate(CalendarDay day) {
return true;
}
@override
public void decorate(DayViewFacade view) {
view.setSelectionDrawable(drawable);
}
}

<?xml version="1.0" encoding="utf-8"?>
<selector xmlns:android="http://schemas.android.com/apk/res/android" android:exitFadeDuration="@android:integer/config_shortAnimTime">

    <item android:drawable="@drawable/ic_my_selector" android:state_checked="true" />

    <item android:drawable="@drawable/ic_my_selector" android:state_pressed="true" />

    <item android:drawable="@drawable/ic_my_default" />

</selector>

**Comment by Hafijur-rahman** [comment]
thanks for your support

**Comment by eltohamy** [comment]
Welcome
