### ISSUE TITLE
I cant inflate your view.Please fix this issue.My xml code is below

### ISSUE THREAD

**Issue by mehmetpeker** [eltohamy/material-hijri-calendarview#8]
android.view.InflateException: Binary XML file line #27: Error inflating class com.github.eltohamy.materialhijricalendarview.MaterialHijriCalendarView

 <com.github.eltohamy.materialhijricalendarview.MaterialHijriCalendarView
                    android:id="@+id/calendar_hijri"
                    android:layout_width="match_parent"
                    android:layout_height="wrap_content"
                    xmlns:app="http://schemas.android.com/apk/res-auto"
                    app:mcv_showOtherDates="all"
                    app:mcv_selectionColor="#00F"
                    />

**Comment by eltohamy** [comment]
make sure you add the library to gradle file.
