### ISSUE TITLE
Can't find resource for bundle 'com.github.msarhan.ummalqura.calendar.text.UmmalquraFormatData_tr_TR', key ''

### ISSUE THREAD

**Issue by mehmetpeker** [eltohamy/material-hijri-calendarview#9]
Please help me? How can i resolve this issue?
Can't find resource for bundle 'com.github.msarhan.ummalqura.calendar.text.UmmalquraFormatData_tr_TR', key ''

**Comment by eltohamy** [comment]
make sure your gradle contains com.github.msarhan.ummalqura
